config/routes.rb
Rails.application.routes.draw do
  devise_for :students
  root 'events#index'
  resources :students,only:[:show,:edit,:update] 
    resources :groups, only:[:show,:edit, :update] do
    # resources :applies, only:[:update,:edit,:create] do
    # 検索した値がパスに含まれるようなルーティングを生成
      collection do
        get 'search'
      end
      resources :events,except:[:index] 
  end
  
  resources :events,only:[:index] do
    resources :student_events, only:[:new,:create,:destroy, :index]
      collection do
        get 'search'
      end
  end
  
  get '/form'=>'events#form'
  get '/group/login'=>'groups#group_login'
  get '/group/logout'=>'groups#group_logout'
  get '/student_events/:id/events/:event_id/delete'=>'student_events#delete_confirm',as: :apply_delete
end

app/models/student.rb
class Student < ApplicationRecord
  has_one_attached :avatar

  # Include default devise modules. Others available are:
  # , :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable,:confirmable
         
  has_many :student_events, dependent: :destroy
  has_many :events, through: :student_events
  has_many :student_groups, dependent: :destroy
  has_many :groups, through: :student_groups
  accepts_nested_attributes_for :student_groups
 
  validates :password, confirmation: true,on: :create
  validates :password_confirmation, presence: true,on: :create
  validates_presence_of  :password,:grade,:email,on: :create
  validates :intro,    length: { maximum: 60 }   
  
  def full_profile?
    name?&&preference?&&intro?&&avatar.attached?  
  end
  
  #current_studentがgroupとしてログインしていて、かつ、閲覧中のページのグループが引数
  def group_authorized(group)
    if self.groups.present?
      if self.student_groups.first.authority?
        if self.groups.first.id == group.id
          return true
        else
          return false
        end
      end
    else
      return false
    end
  end
  
  #current_studentがgroupとしてログインしているかどうかを調べる
  def group_logged_in
    if self.groups.present?
      if self.student_groups.first.authority
        return true
      end
    else
      return false
    end
  end
  
end

app/controllers/students_controller.rb
class StudentsController < ApplicationController
  
  def show
    @student = Student.find(params[:id])
    @events = @student.events.page(params[:page]).per(3).all.order("created_at DESC")
    if @student == current_student
      if current_student.groups.present?
        @group = current_student.groups.first
      end
    end
  end
  
  def edit
    @student = Student.find(params[:id])
     unless  current_student.id == @student.id
       redirect_to :show
     end
  end
  
  def update
    @student = Student.find(params[:id])
    if @student.id == current_student.id
      if update_params[:avatar].present?
        current_student.avatar.attach(update_params[:avatar])
      end
      current_student.update(update_params)
    end
    redirect_to controller_path: 'show', id: @student.id
  end
  
 private
  def update_params
    params.require(:student).permit(:name, :preference, :grade, :intro, :avatar)
  end
end

app/helpers/students_helper.rb
module StudentsHelper
end

app/views/students/edit.html.erb
<div class="row form">
  <div class="col-lg-12">
   
      <div class="col-xs-10 col-lg-4">
          
        <div class="profile">
            <!--このリンクに飛べるのは@student==current_studentの時のみ-->
          <%= form_with model: @student, url: :student do |f| %>
              <% if current_student.avatar.attached? %>
                <div class="icon_image" style="background-image: url(<%= rails_representation_path(current_student.avatar.variant(combine_options:{resize:"100x100^",crop:"100x100+0+0",gravity: :center}).processed) %>) "></div>
              <% else %>
                <div class="icon_image" style="background-color: gray "></div>
              <% end %>
              
              <div class="form-group file">
                   <%= f.file_field :avatar, placeholder: "画像を変更する", autofocus: true , class: "form-control"%>
              </div>
             
              
               <!--<div class="col-xs-8 col-lg-3">-->
                 <div class="profile_wrapper">
                     <div class="profile_wrapper_edit">
                       <h3><span class="gray">名前：</h3>
                       <%= f.text_field :name, placeholder: "名前", autofocus: true, class: "form-control" %>
                   </div>
                 </div>
               <!--</div>-->
               
               <!--<div class="col-xs-8 col-lg-3">-->
                 <div class="profile_wrapper">
                     <div class="profile_wrapper_edit">
                        <h3><span class="gray">学年：</h3>
                        <%= f.select :grade,[ ['1回生', 1],['2回生', 2],['3回生', 3],['4回生', 4]], selected: current_student.grade,placeholder: "学年", class: "form-control"  %>
                     </div>
                 </div>
               <!--</div>-->
               
               <!--<div class="col-xs-8 col-lg-3">-->
                 <div class="profile_wrapper">
                     <div class="profile_wrapper_edit">
                      
                        <% unless current_student.grade==1%>
                        <h3><span class="gray">所属：</h3>
                          <%= f.collection_select :preference, Group.all, :name, :name, :include_blank => true  %>
                        <% else %>
                         <h3><span class="gray">希望：</h3>
                           <%= f.collection_select :preference, Group.all, :name, :name, :include_blank => true  %>
                        <% end %>
                     </div>
                 </div>
               <!--</div>-->
               
               <!--<div class="col-xs-8 col-lg-3">-->
                 <div class="profile_wrapper">
                     <div class="profile_wrapper_edit">
                          <h3><span class="gray">紹介：</h3>
                          <%= f.text_field :intro, placeholder: "自己紹介※最大60文字", maxlength: "60" ,class:"form-control"%>
                     </div>
                 </div>
               <!--</div>-->
               
                <!--<div class="col-xs-8 col-lg-3">-->
                  <div class="form-save">
                    <%= f.submit "保存", class:"button_save" %>
                  </div>
               <!--</div>-->
          <% end %>
          <%= link_to student_path(current_student) do%>
            <%= image_tag "back.png" %>
          <% end %>
          
        </div>  
      </div>
   
  </div>
</div>

app/views/students/show.html.erb
<div class="row form">
  <div class="col-lg-12">
    <div class="col-xs-10 col-lg-4">
      <div class="profile">
        <% if @student.full_profile? %>
           <% if @student.avatar.attached? %>
             <div class="icon_image" style="background-image: url(<%= rails_representation_path(@student.avatar.variant(combine_options:{resize:"100x100^",crop:"100x100+0+0",gravity: :center}).processed) %>) ">
              </div>
           <% else %>
             <div class="icon_image" style="background-color: gray"></div>
           <% end %>
           
           <% if current_student.id==@student.id %>
             <%= link_to  edit_student_path(current_student), { class: "edit" } do %>
               <%= image_tag "edit.png" %>
             <% end %>
           <% end %>
              
            <h2><%=@student.name%></h2>
              <div class="profile_wrapper">
                <h3><span class="gray">学年：</span><%= @student.grade%>回生</h3></br>
              </div>
              <div class="profile_wrapper">
                <% if @student.grade==1 %>
                  <h3><span class="gray">希望体：</span><%= @student.preference%></h3></br>
                <% else %>
                  <h3><span class="gray">所属：</span><%= @student.preference%></h3></br>
                <% end %>
             </div>
             <div class="intro">
               <div class="profile_wrapper">
                  <h3><span class="gray">自己紹介：</span><%= @student.intro %></h3>
               </div>
            </div>
          
        <% else %>   <!--プロフィールが完成していないなら-->
           <% if current_student.id == @student.id %>
             <%= link_to "プロフィールを完成させよう！", edit_student_path(@student), class:"complete" %>
           <% else %>
             <h3>まだプロフィールが作成されていません</h3>
           <% end %>
        <% end %>
      </div>  <!--profile-->
      <div class="var">
       <% if current_student.id == @student.id %>
         <div class="var_half">
            <%= link_to "ログアウト", destroy_student_session_path, method: :delete %>
         </div>
         <div class="var_half">
           <% if @group.present? %>
               <%= link_to 'グループアカウント',group_login_path %>
           <% end %>
         </div>
       <% end %>
      </div>
    </div>
    <% if @events.present? %>
      <div class="event_index">
        <h2>応募一覧</h2>
          <% current_student.events.each do |event| %>
            <%= render partial: "common/event", locals: { event: event } %>
          <% end %>
          <%= paginate(@events) %>
      </div> 
    <% end %>
  </div>
</div>

  

app/views/students/update.html.erb
 <h2>プロフィールを編集しました！</h2>
 <%= link_to 'マイページへ戻る',student_path(current_student)  %>