config/routes.rb
Rails.application.routes.draw do
  devise_for :students
  root 'events#index'
  resources :students,only:[:show,:edit,:update] 
    resources :groups, only:[:show,:edit, :update] do
    # resources :applies, only:[:update,:edit,:create] do
    # 検索した値がパスに含まれるようなルーティングを生成
      collection do
        get 'search'
      end
      resources :events,except:[:index] 
  end
  
  resources :events,only:[:index] do
    resources :student_events, only:[:new,:create,:destroy, :index]
      collection do
        get 'search'
      end
  end
  
  get '/form'=>'events#form'
  get '/group/login'=>'groups#group_login'
  get '/group/logout'=>'groups#group_logout'
  get '/student_events/:id/events/:event_id/delete'=>'student_events#delete_confirm',as: :apply_delete
end

app/models/group.rb
class Group < ApplicationRecord

  has_one_attached :image 
   
  # 親テーブルのデータが消えたら子テーブル(student_groups)のデータも消す
  has_many :student_groups, dependent: :destroy
  has_many :students, through: :student_groups
  accepts_nested_attributes_for :student_groups
  
  has_many :events, dependent: :destroy
 
  validates :category,  length: { maximum: 5 }     
  validates :what_to_do,  length: { maximum: 10 }     
  validates :intro, length: { maximum: 60 }   
  validates_presence_of :name,:what_to_do,:category,:intro ,:image, on: :update
 
  def full_profile?
   name? && category? && what_to_do? && intro? && image.attached?  
  end
  
  # def group_authorized?(current_student)
  #   if current_student.authorized?
  #     if current_student.groups.first.id == self.id
  #       return true
  #     end
  #   else
  #     return false
  #   end
  # end
       
end

app/controllers/groups_controller.rb
class GroupsController < ApplicationController
    require 'date'
#   before_action :move_to_top unless current_student.group
    
    def show 
      @conne = StudentGroup.find_by(student_id: current_student.id)
      @group = Group.find(params[:id])
      @events = @group.events.order("created_at DESC").page(params[:page]).per(3)
      @today = Date.today
    end
    
    def search
      @groups = Group.where('name LIKE(?)', "%#{params[:g_keyword]}%" ).page(params[:page])
      @g_keyword = "#{params[:g_keyword]}"
    end
    
    def edit
      @group = Group.find(params[:id])
      if @group.authorized?(current_student)
        @group = current_student.groups.first
        @grade = current_student.grade
      else
        redirect_to :group
      end
    end
    
    def update
    @group = Group.find(params[:id])
      if  @group.authorized?(current_student)
        current_student.groups.first.update(update_params)
        flash.notice = "プロフィールを更新しました"
        redirect_to :group
      else
        redirect_to :group
      end
    end
    
  def group_login
    @association = StudentGroup.find_by(student_id: current_student.id)
    login(@association)
    redirect_to controller: 'groups', action: 'show', id: @association.group_id
  end
  
  def group_logout
    @association = StudentGroup.find_by(student_id: current_student.id)
    logout(@association)
    redirect_to controller: 'students', action: 'show', id: current_student.id
  end
    
  private
    def move_to_top
      redirect_to  controller: 'students', action: 'show'
    end
    
    def update_params
      params.require(:group).permit(:name,:category,:what_to_do,:intro,:image)
    end
    
    def login(student_group)
      student_group.authority = true
      student_group.save
    end
  
    def logout(student_group)
        student_group.authority = false
        student_group.save
    end

end

app/helpers/groups_helper.rb
module GroupsHelper
end

app/views/groups/edit.html.erb
<div class="row form">
  <div class="col-lg-12">
     <div class="col-xs-10 col-lg-4">
        <div class="profile">
          <%= form_with model: @group,url: :group do |f| %>
             <!--<div class="image" style="background-image: url(%= rails_blob_path(@group.image) %>) ">-->
             <% if @group.image.attached? %>
               <div class="icon_image" style="background-image: url(<%= rails_representation_path(@group.image.variant(combine_options:{resize:"100x100^",crop:"100x100+0+0",gravity: :center}).processed) %>) "></div>
            <% else %>
               <div class="icon_image" style="background-color: gray "></div>
            <% end %>
            <div class="form-group file">
               <%= f.file_field :image, placeholder: "画像アップロード", autofocus: true ,  class: "form-control floating-label" %>
            </div>
           
            <!--<div class="col-xs-8 col-lg-3">-->
                 <div class="profile_wrapper">
                     <div class="profile_wrapper_edit">
                         <h3><span class="gray">名前：</span></h3>
                         <%= f.text_field :name, placeholder: "団体名",autofocus: true, class: "form-control" %>  
                     </div>
                 </div>
            <!--</div>-->
            
             <!--<div class="col-xs-8 col-lg-3">-->
                 <div class="profile_wrapper">
                   <div class="profile_wrapper_edit">
                         <h3><span class="gray">分類：</span></h3>
                      <%= f.text_field :category,　placeholder: "サークル/体育会",maxlength: "5" , class: "form-control"  %> 
                   </div>
                 </div>
            <!--</div>-->
            
             <!--<div class="col-xs-8 col-lg-3">-->
                 <div class="profile_wrapper">
                     <div class="profile_wrapper_edit">
                       <h3><span class="gray">活動：</span></h3>
                       <%= f.text_field :what_to_do, placeholder: "例)バスケ/ボランティア※最大10文字", maxlength: "10" , class: "form-control"%>           
                  </div>
                  </div>
            <!--</div>-->
            
             <!--<div class="col-xs-8 col-lg-3">-->
                 <div class="profile_wrapper">
                   <div class="profile_wrapper_edit">
                       <!--<div class="intro">-->
                            <h3><span class="gray">紹介：</span></h3>
                            <%= f.text_field :intro, placeholder: "特徴/アピールポイント※最大60文字" ,  maxlength: "60" , class: "form-control"%>  
                       <!--</div>-->
                    </div>
                 </div>
            <!--</div>-->
            
            <!--<div class="col-xs-8 col-lg-3">-->
              <div class="form-save">
                <%= f.submit "保存", class:"button_save" %>
              </div>
            <!--</div>-->
         <% end %>
            <%= link_to group_path(@group) do%>
              <%= image_tag "back.png" %>
            <% end %>
        </div>
    
      </div>
  </div>
</div>

app/views/groups/search.html.erb
<% if @g_keyword.blank?  %>
  <div class="apply_form">
    <p>キーワードを入力してください</p>
  </div>
   
<% else %>
  <% if @groups.blank? %>
    <div class="apply_form">
      <p><%= @g_keyword %>に対応するイベントは存在しません</p>
      <p>他のキーワードで検索してください</p>
    </div>
  <% else %>
    <div class="event_index">
      <% @groups.each do |group| %>
        <div class="event">
          <div class="event_bottom">
            <%= render partial: "common/group", locals: {  group: group } %>
          </div>
        </div>
      <% end %>
    <%= paginate(@groups) %>
    </div>
  <% end %>  
<% end %>

<%= link_to form_path  do %>
  <%= image_tag "back.png" %>
<% end %>

app/views/groups/show.html.erb
<div class="row form">
  <div class="col-lg-12">
    <div class="col-xs-10 col-lg-4">
      <div class="profile">
        <% if @group.full_profile? %>
          <% if @group.image.attached? %>
            <div class="icon_image" style="background-image: url(<%= rails_representation_path(@group.image.variant(combine_options:{resize:"100x100^",crop:"100x100+0+0",gravity: :center}).processed) %>) "></div>
          <% else %>
            <div class="icon_image" style="background-color: gray ">
          <% end %>
          <% if current_student.group_authorized(@group) %>
            <%= link_to edit_group_path(@group), { class:"edit" }  do %>
              <%= image_tag "edit.png",:class => 'edit_student',:alt => 'edit_student' %>
            <% end %>
          <% end %>
          <h2><%= @group.name %></h2>
           <div class="profile_wrapper">
             <h3><span class="gray">分類：</span><%= @group.category %></h3>
           </div>
            <div class="profile_wrapper">
              <h3><span class="gray">活動：</span><%= @group.what_to_do%></h3>
            </div>
            <div class="intro">
              <div class="profile_wrapper">
                <h3><span class="gray">紹介：</span> <%= @group.intro.blank??   "このグループの説明はありません" : @group.intro %></h3>
              </div>
            </div>
        <% else %> <!--full_profile?がfalseなら-->
          <% if current_student.group_authorized(@group)  %>
              <%= link_to "プロフィールを完成させよう", edit_group_path(@group), class:"complete" %>
          <% else %>
           <h3 style="text-align: center">まだプロフィールがありません</h3>
          <% end %>
        <% end %>
      </div>
     <div class="var">
      <% if current_student.group_authorized(@group) %>
        <div class="var_half">
          <%= link_to 'ユーザーアカウントへ', group_logout_path %>
        </div>
      <% end %>
     </div>
  </div>
    <div class="col-xs-10 col-lg-4">
      <% if @events.present? %>
        <h2><%= @group.name %>の新歓一覧 </h2>
        <div class="event_index">
          <% if current_student.group_authorized(@group) %>
            <%= link_to  new_group_event_path(@group), method: :get do %>
              <%= image_tag "new_event.png", :class => 'new_event' , :alt => 'new_event'%>
            <% end %>
          <% end %>
          <% @events.each do |event| %>
            <%= render partial: "common/event", locals: { event: event, group: @group } %>
          <% end %>
       </div>
      <%= paginate(@events) %>
      <% else %>
        <div class="event_index">
          <div class="event_none">
            <p>まだイベントはありません</p>
            <% if current_student.group_authorized(@group) %>
              <%= link_to "イベントを作成する",new_group_event_path(@group), class:"button"  %>
            <% end %>
           </div>
         </div>
      <% end %>
    </div> 
  </div>
</div>