config/routes.rb
Rails.application.routes.draw do
  devise_for :students
  root 'events#index'
  resources :students,only:[:show,:edit,:update] 
    resources :groups, only:[:show,:edit, :update] do
    # resources :applies, only:[:update,:edit,:create] do
    # 検索した値がパスに含まれるようなルーティングを生成
      collection do
        get 'search'
      end
      resources :events,except:[:index] 
  end
  
  resources :events,only:[:index] do
    resources :student_events, only:[:new,:create,:destroy, :index]
      collection do
        get 'search'
      end
  end
  
  get '/form'=>'events#form'
  get '/group/login'=>'groups#group_login'
  get '/group/logout'=>'groups#group_logout'
  get '/student_events/:id/events/:event_id/delete'=>'student_events#delete_confirm',as: :apply_delete
end

app/models/event.rb
class Event < ApplicationRecord
  # attr_accessor :group_id
  has_one_attached :image 
  has_many :student_events, dependent: :destroy
  has_many :students, through: :student_events
  # accepts_nested_attributes_for :appresence: true
  # 画像はつけなくてもevent作成可能
  validates_presence_of  :title,:image,:date,:descrip, :where,:group_id
  # whereは20字
  validates :where, length: { maximum: 20 }     
  # descripは40字
  validates :descrip, length: { maximum: 50 } 
  
  belongs_to :group
  
  
end

app/controllers/events_controller.rb
class EventsController < ApplicationController
  
  before_action :move_to_top, only: [:update, :edit, :destroy,:new,:create]
  
  def index
    @events = Event.includes(:group).all.order("date DESC").page(params[:page]).per(4)
    @apply = StudentEvent.find_by(student_id: current_student.id)
  end
  
  def new
    @group = Group.find(params[:group_id])
    @event = Event.new
  end 
  
  def create
    group = Group.find(params[:group_id])
    Event.create(title: params_permit[:title], date: params_permit[:date], where: params_permit[:where], descrip: params_permit[:descrip], image:  params_permit[:image],group_id: group.id )
    flash.notice = "イベントを追加しました"
    redirect_to controller: 'groups', action: 'show', id: group.id
  end
  
  def edit
    @event =Event.find(params[:id])
    @group = Group.find(params[:group_id])
  end
  
  def update
    group = Group.find(params[:group_id])
    event = Event.find(params[:id])
    event.update(params_permit)
    flash.notice = "イベントを更新しました"
    redirect_to controller: 'groups', action: 'show', id: group.id
  end
  
  def destroy
    @group = Group.find(params[:group_id])
    event = Event.find(params[:id])
      event.destroy!
    flash.notice = "イベントを削除しました"
    redirect_to controller: 'groups', action: 'show', id: @group.id
  end

  def show
    group = Group.find(params[:group_id])
    redirect_to controller: 'groups', action: 'show', id: group.id
  end
  
  def form
  end
  
  def search
    @events = Event.where(['title LIKE (?)', "%#{params[:e_keyword]}%"]).page(params[:page])
    @e_keyword = "#{params[:e_keyword]}"
  end
  
  private
    def params_permit
      params.require(:event).permit(:title,:date,:descrip,:where,:image)
    end
    
    def move_to_top
      group = Group.find(params[:group_id])
      unless current_student.group_authorized(group)
        flash.alert = "権限がありません"
        redirect_to root_path and return
      end
    end
  
end

app/helpers/events_helper.rb
module EventsHelper
end

app/views/events/edit.html.erb
<div class="row form">
  <div class="col-lg-12">
<!--ルーティングのパスはgroup_event_pathだが、form_forが求めてるタグはgroup_events_path-->
<!--なので　url: group_event_path として無理やり単数形のパスにつなげる-->
<div class="col-xs-10 col-lg-4">
   
  <div class="profile">
    <%= form_with model: @event ,url: :group_event do |f| %>
      <% if @event.image.attached? %>
         <div class="event_image"><%= image_tag @event.image.variant(combine_options:{resize:"400x100^",crop:"400x100+0+0",gravity: :center}).processed %></div>
      <% else %>
         <div class="event_image" style="background-color: gray;"></div>
      <% end %>
      
      <div class="form-group file">
        <%= f.file_field :image, placeholder: "画像を変更する", autofocus: true , class: "form-control floating-label"%>
      </div>
      
         <div class="col-xs-8 col-lg-3">
             <div class="profile_wrapper">
                <div class="profile_wrapper_edit">
                  <h3><span class="gray">名前：</h3>
                  <%= f.text_field :title, placeholder: "名前",autofocus: true %>         
                </div>       
             </div>
         </div>
         
          <div class="col-xs-8 col-lg-3">
             <div class="profile_wrapper">
                <div class="profile_wrapper_edit">
                  <h3><span class="gray">日付：</h3>
                     <%= f.date_field :date, placeholder: "開催日時" %>         
                </div>       
             </div>
         </div>
         
         <div class="col-xs-8 col-lg-3">
             <div class="profile_wrapper">
                <div class="profile_wrapper_edit">
                  <h3><span class="gray">場所：</h3>
                   <%= f.text_field :where, placeholder: "開催場所※最大20",maxlength: "20" ,required: true %>           
                </div>       
             </div>
          </div>
          <div class="col-xs-8 col-lg-3">
             <div class="profile_wrapper">
                <div class="profile_wrapper_edit">
                 <h3><span class="gray">説明：</h3>
                 <%= f.text_field :descrip, placeholder: "説明※最大20",maxlength: "20" ,required: true %> 
                  <!--%= f.text_field :descrip, placeholder: "詳細※最大50文字",maxlength: "50"　,required: true %>           -->
                </div>       
             </div>
         </div>
         
         
         
         
          <div class="col-xs-8 col-lg-3">
             <div class="form-save">
                    <%= f.submit "保存" ,class:"button_save",required: true %> 
             </div>
         </div>
        
         <%= link_to group_path(@group)  do %>
         <%= image_tag "back.png" %>
        <% end %>
         
    <% end %>
    
    </div>
    </div>
   
    
  </div>
</div>

app/views/events/form.html.erb
<div class="search_wrapper">
  <div class="col-xs-8 col-lg-6">
    <div class="search_left">
       <div class="search">
        <%= image_tag "search.png" %>
          <%= form_tag(search_events_path, method: :get,class: "form-group") do %>
          <input placeholder="イベント名" name="e_keyword" maxlength= 10 type="text" class="form-controller">
        <% end %>
     </div>
    </div>
  </div>
   
  <div class="col-xs-8 col-lg-6">
    
    <div class="search">
      <%= form_tag(search_groups_path, method: :get,class: "form-group") do %>
        <input placeholder="団体名" name="g_keyword" maxlength= 10 type="text" class="form-controller">
      <% end %>
    </div>
  </div>
   
</div>

app/views/events/index.html.erb
<div class="event_index">
  <% @events.each do |event| %>
  <!--<div class="background_image" style="background-image: url('images.jpg')">-->
    <%= render partial: "common/event", locals: { event: event,apply: @apply} %>
  <% end %>
  <%= paginate(@events) %>
</div>

app/views/events/new.html.erb
<div class="row form">
 <div class="col-lg-12">
<!--ルーティングのパスはgroup_event_pathだが、form_forが求めてるタグはgroup_events_path-->
<!--なので　url: group_event_path として無理やり単数形のパスにつなげる-->
<!--としてたけど適切なモデルを引き渡せないので-->
   <div class="col-xs-10 col-lg-4">
       <div class="profile">
      <%= form_with model: @event , url: :group_events do |f| %>
      
       <div class="form-group file">
         <%= f.file_field :image, placeholder: "画像アップロード", autofocus: true ,  class: "form-control floating-label" %>
       </div>
      
       <div class="col-xs-8 col-lg-3">
         <div class="profile_wrapper">
            <div class="profile_wrapper_edit">
              <h3><span class="gray">名前：</h3>
                <%= f.text_field :title, placeholder: "名前",autofocus: true,required: true %>
            </div>
          </div>
       </div>
       
       <div class="col-xs-8 col-lg-3">
         <div class="profile_wrapper">
            <div class="profile_wrapper_edit">
              <h3><span class="gray">日時：</h3>
                 <%= f.date_field :date, placeholder: "開催日時" ,required: true %>
            </div>
          </div>
       </div>
       
       <div class="col-xs-8 col-lg-3">
         <div class="profile_wrapper">
            <div class="profile_wrapper_edit">
              <h3><span class="gray">場所：</h3>
                <%= f.text_field :where, placeholder: "開催場所※最大20文字",maxlength: "20" ,required: true%>
            </div>
          </div>
       </div>
       
        <div class="col-xs-8 col-lg-3">
         <div class="profile_wrapper">
            <div class="profile_wrapper_edit">
              <h3><span class="gray">説明：</h3>
                <%= f.text_field :descrip, placeholder: "詳細※最大40文字", maxlength: "40"  ,required: true%>
            </div>
          </div>
       </div>
       
        <div class="col-xs-8 col-lg-3">
           <div class="form-save">
             <!--おかしなURLにとんでしまう-->
             <%= f.submit "保存" ,class:"button_save" %>          
           </div>
        </div>
           
      <% end %>
      
       <%= link_to group_path(@group) do%>
         <%= image_tag "back.png" %>
       <% end %>
       
       </div>
    </div>
  </div>
</div>

app/views/events/search.html.erb
<% if @e_keyword.blank?  %>
  <div class="apply_form">
      <p>キーワードを入力してください</p>
  </div>
<% else %>
  <% if @events.present? %>
    <div class="event_index">
      <% @events.each do |event| %>
      <!--<div class="image" style="background-image: url(%= rails_blob_path(event.group.image) %>) "></div>-->
        <%= render partial: "common/event", locals: { event: event } %>
      <% end %>
     <%= paginate(@events) %>
    </div>
   
  <% else %>
   <div class="apply_form">
     <p><%= @e_keyword %>に対応するイベントは存在しません</p>
     <p>他のキーワードで検索してください</p>
   </div>
  <% end %>
  
<% end %>

<%= link_to form_path  do %>
  <%= image_tag "back.png" %>
<% end %>