config/routes.rb
Rails.application.routes.draw do
  devise_for :students
  root 'events#index'
  resources :students,only:[:show,:edit,:update] 
    resources :groups, only:[:show,:edit, :update] do
    # resources :applies, only:[:update,:edit,:create] do
    # 検索した値がパスに含まれるようなルーティングを生成
      collection do
        get 'search'
      end
      resources :events,except:[:index] 
  end
  
  resources :events,only:[:index] do
    resources :student_events, only:[:new,:create,:destroy, :index]
      collection do
        get 'search'
      end
  end
  
  get '/form'=>'events#form'
  get '/group/login'=>'groups#group_login'
  get '/group/logout'=>'groups#group_logout'
  get '/student_events/:id/events/:event_id/delete'=>'student_events#delete_confirm',as: :apply_delete
end

app/views/common/_event.html.erb
<div class="col-xs-10 col-lg-4">
  <div class="event">
   
       <% if event.image.attached? %>
         <div class="event_image"style="background-image: url(<%= rails_representation_path(event.image.variant(combine_options:{resize:"400x100^",crop:"400x100+0+0",gravity: :center}).processed) %>) ">
         </div>
         <% else %>
         <div class="event_image" style="background-color: gray;"></div>
      <% end %>
      <div class="event_content">
        <div class="event_title">
          <h3><%= event.title %></h3>
        </div>
         <div class="event_descrip">
            <ul class="descrip">
                <li>
                  <p>日時：<%= event.date.month %>/<%= event.date.day %></p>
                </li>
                <li>
                  <p>場所：<%= event.where %></p>
                </li>
            </ul>
            <%= simple_format(event.descrip)%>
          </div>
      </div>
    
    <div class="event_bottom">
         <%= render partial: "common/group", locals: { group: event.group } %>
      <% if current_student.student_groups.present? %>
        <% if  current_student.student_groups.first.authority %>
          <% if event.group.id == current_student.groups.ids.first%>
          <div class="atag_wrapper">
            <%= link_to edit_group_event_path(event.group,event), method: :get  do %>
              <%= image_tag "edit.png", :class => 'edit_event',:alt => 'edit_event' %>
            <% end %>
            <%= link_to group_event_path(event.group,event), method: :delete do  %>
              <%= image_tag "delete.png", :class => 'delete_event',:alt => 'delete_event' %>
            <% end %>
          </div>
         <% end %>
       <% else %>
           <%= render partial: "common/student_event", locals: { event: event } %>
       <% end %>
      <% else %>
        <%= render partial: "common/student_event", locals: { event: event } %>
      <% end %>
    </div>
  </div>
</div>

app/views/common/_footer.html.erb
<footer class="fixed-bottom">
  <!--ユーザーがログインしてるならという条件をこのファイルを呼び出す前に行う-->
  <div class="footer_wrapper">
    <div class="icon">
         <%= link_to root_path do %>
           <%= image_tag "home.png" %>
         <% end %>
     </div>
      <div class="icon">
          <%= link_to  form_path do %>
            <%= image_tag "search.png" %>
          <% end %>
      </div>
     <div class="icon">
        <% if current_student.group_logged_in %>
            <%= link_to group_path(current_student.groups.first) do  %>
              <%= image_tag "profile.png" %>
            <% end %>
        <% else %>
            <%= link_to student_path(current_student) do %>
              <%= image_tag "profile.png" %>
            <% end %>
       <% end %>
    </div>
  </div>
</footer>

app/views/common/_group.html.erb
<% if group.image.attached? %>
  <div class="group_image" style="background-image: url(<%= rails_representation_path(group.image.variant(combine_options:{resize:"100x100^",crop:"100x100+0+0",gravity: :center}).processed) %>) ">
  </div>
<% else %>
  <div class="group_image" style="background-color: gray ">
  </div>
<% end %>
<div class="event_group">
  <%= link_to "#{group.name}",  group_path(group), method: :get , class: "group"%>
</div>

app/views/common/_student_event.erb
<% if event.student_events.where(student_id: current_student.id).where(event_id: event.id).present? %>
  <%= link_to 'キャンセル', apply_delete_path(event.student_events.where(student_id: current_student.id).where(event_id: event.id).first.id,event.id), method: :get , class: "apply" %>
<% else %>
  <%= link_to '参加する', new_event_student_event_path(event.id), method: :post , class: "apply" %>
<% end %>